.github/workflows/array-api.yml, pixi.lock, pixi.toml
Array API tests [broke](https://github.com/Quantco/ndonnx/actions/runs/9512798575/job/26221554808#step:5:751) during the pixi migration. This PR also uses the standard GitHub actions runner again.
=> Add ndindex back for Array API tests

.github/workflows/ci.yml, README.md, docs/experimental/experimental.rst, docs/intros/gettingstarted.rst, ndonnx/_data_types/classes.py, ndonnx/_data_types/structtype.py, pixi.lock, pixi.toml, tests/ndonnx/test_compute_modes.py, tests/ndonnx/test_core.py, tests/ndonnx/test_dtypes.py, tests/ndonnx/test_masked.py, tests/ndonnx/utils.py
With the release of NumPy 2.0 earlier this week, [Array API support was promoted](https://numpy.org/doc/stable/release/2.0.0-notes.html#highlights) to the main ``numpy`` namespace.
This updates the lockfile. It also updates the documentation and tests to remove the use of ``numpy.array_api``.
=> Update to numpy 2.0

CHANGELOG.rst, ndonnx/_array.py
Please note that while the version we support is 2023.12, we still have some missing functionality: https://github.com/Quantco/ndonnx/issues/6.
=> Update __array_namespace__ to accept api_version.

CHANGELOG.rst, ndonnx/__init__.py, ndonnx/_data_types/__init__.py
`promote_nullable` is publicly exposed, but it's not working because it is not imported properly in the init file.
Add import `promote_nullable` in `ndonnx.__init__`
=> Fix public export promote_nullable

CHANGELOG.rst, ndonnx/_core/_impl.py, skips.txt, tests/ndonnx/test_core.py
The Array API standard states that the output of `divide` must be a floating-point output. This PR ensures that that is the case.
After:
```
>>> ndx.asarray(2)/3
Array(0.6666666666666666, dtype=Float64)
```
Before:
```
>>> ndx.asarray(2)/3
Array(0, dtype=Int64)
```
=> Fix true division integer casting.

ndonnx/_funcs.py
zeros_like needs an explicite dtype, otherwise it will try to cast the value to the dtype of the original array. This can fail for user-defined data types.
=> Fix broadcast_arrays for user-defined data types

ndonnx/_core/_impl.py
Previously `ndx.where(ndx.asarray([True, False]), ndx.asarray([0, 1], ndx.int8), ndx.asarray([2, 3], ndx.int8))` would yield an `int32` output. This upcasting is due to the fact that onnxruntime does not implement `int8` and `int16` kernels, but a respective downcast should exist so the output of `ndx.where` has the dtype of its promoted arguments.
=> Cast back to input dtype in `where`

ndonnx/_core/_impl.py, tests/ndonnx/test_core.py
Onnxruntime doesn't implement ``ReduceProd`` for ``float64``. We will error for
``float64`` and otherwise use ``float32``.
Also fixes the implementation for unsigned integers
=> Use ``float32`` in ``where``

ndonnx/_funcs.py, tests/ndonnx/test_core.py
Currently, because the ONNX shape operator requires a 1D tensor as input, doing `ndx.full` with a scalar and lazy shape fails. This PR adds the extra dimension if the rank of the shape is 0. 
Note that we generally expect the rank to be known statically from ONNX shape inference and `ndx.Array.ndim` returns an int. You can construct specific cases where even the rank is data-dependent.
=> Allow `full` to work with scalar shapes.

tests/test_core.py
The shape inference fails when inputs are eager. Added a xfail test case for it.
=> Add tests for concat with empty array

ndonnx/_core/_impl.py, ndonnx/_utility.py, tests/test_core.py
The previous promotion improvement neglected to account for cross-kind promotions between bools, ints and floats. These were automatically handled in the previous implementation. This leads to results like the following, which are resolved in this PR:
```
(Pdb) np.asarray([1, 2]) + 2.32
array([3.32, 4.32])
(Pdb) ndx.asarray([1, 2]) + 2.32
Array([3 4], dtype=Int64)
```
=> Fix cross-kind promotions

ndonnx/_funcs.py
Small mistake in the error message is printed if a dtype has not implemented `full_like`.
=> Fix error message if full_like is not implemented

ndonnx/_core/__init__.py, ndonnx/_core/_boolimpl.py, ndonnx/_core/_nullableimpl.py, ndonnx/_core/_numericimpl.py, ndonnx/_core/_stringimpl.py, ndonnx/_data_types/classes.py, ndonnx/_funcs.py
This PR splits out implementations of functions for nullable dtypes. It doesn't take things very far and only fixes a bug around `make_nullable`.
We should take this further and start moving actual null handling out of the `via_dtype` functions and into the dtype implementation after the upcoming release.
=> Split out nullable implementation block

ndonnx/_core/_shapeimpl.py, tests/test_core.py
Before, when `where` got two identical nullable arrays, the type got changed to non-nullable.
=> Fix `where` changing dtype of nullable arrays

CHANGELOG.rst, ndonnx/_array.py, tests/test_iter.py
Running the scikit-learn test suite on the latest 0.8 release revealed an infinite loop when using arrays in for-loops. Namely, it turns out that the following code currently loops indefinitely:
```python
a = ndx.array(shape=(2,), dtype=ndx.int64)
for item in a:
...
```
Looping like this over a dimension with static size is perfectly safe and reasonable to do. This PR ensures that the iterations over dimension with static length terminate correctly. 
The issue is more delicate for an array with a dynamic length such as in the following example. 
```python
a_dyn = ndx.array(shape=("N",), dtype=ndx.int64)
for item in a_dyn:
...
```
While infinite generators are not uncommon in Python, they only make sense if the user breaks out of the loop in some other way. It seems rather unlikely that …
=> Forbid iteration over dynamic dimensions

ndonnx/_opset_extensions.py, ndonnx/additional/_additional.py, tests/test_additional.py
`static_map` was (probably) originally conceived as a thin LabelEncoder wrapper. This cleans up some issues with non int64 integers and strings.  Closes https://github.com/Quantco/ndonnx/issues/63.
=> Broaden `static_map` support

CHANGELOG.rst, ndonnx/_core/_numericimpl.py, ndonnx/_funcs.py, tests/test_core.py
Closes https://github.com/Quantco/ndonnx/issues/62. It also resolves a couple of Array API discrepancies, namely:
- The semantics of `include_initial` in `cumulative_sum`
- The default for `axis` in `concat`
=> Fix cumulative_sum

ndonnx/_corearray.py, pixi.lock, pixi.toml
These are some very minor drive-by changes. We were stuck on an older version of mypy due to an upper bound.
The `build` package was renamed as described [here](https://conda-forge.org/news/2024/08/21/remove-build/).
=> Minor drive-by fixes

CHANGELOG.rst, pixi.toml
Unfortunately https://github.com/Quantco/ndonnx/pull/77 removed source distributions from ndonnx builds. This PR adds them back.
=> Add back source distributions

.github/workflows/array-api.yml, README.md, pixi.toml
This test enables nightly tests on the Array API, which tests using the "max-examples" set to the default and a non-constant seed. 
The time the action runs is taken from the [last scheduled job](https://github.com/Quantco/ndonnx/actions/runs/10072907802/workflow).
=> Run Array API tests weekly

ndonnx/_core/_numericimpl.py, ndonnx/_core/_shapeimpl.py, ndonnx/_opset_extensions.py, tests/test_core.py, xfails.txt
This PR fixes the weekly failures of the array-api(#92) by:
- disabling `argmin` and `argmax` on the test suite and improving our tests as `onnxruntime` does not implement them for `UInt64`
- reimplements right shift as the array-api defines it as an [arithmetic right shift](https://en.wikipedia.org/wiki/Arithmetic_shift)
- fixes `all` and `any` for non-boolean inputs
- raises errors when possible in `expand_dims` and `getitem_null`
=> Fix weekly failures

ndonnx/_opset_extensions.py, tests/test_core.py
Addresses undefined behavior in onnxruntime as exhibited in https://github.com/Quantco/ndonnx/actions/runs/12972746658/job/36180534245#step:5:3324. We should address this upstream.
=> Zero size matmul mitigation

.github/CODEOWNERS, .github/workflows/array-api.yml
I am removing @neNasko1 as a code owner temporarily due to some org/repo level settings that will need to be re-configured. Currently, this affects our weekly Array API tests: https://github.com/Quantco/ndonnx/actions/runs/12972746658/job/36180534245#step:8:28.
=> Remove @neNasko1 temporarily

ndonnx/__init__.py, ndonnx/_data_types/aliases.py, xfails.txt
I mislabelled the integral kind in https://github.com/Quantco/ndonnx/commit/039264da5587edc5a65ebc6ac2f7f0d0f19176de. It wasn't caught since we skipped a relevant test from upstream.
=> Address xfails and mislabelled kind

tests/conftest.py, tests/schemas/bool.json, tests/schemas/float32.json, tests/schemas/float64.json, tests/schemas/int16.json, tests/schemas/int32.json, tests/schemas/int64.json, tests/schemas/int8.json, tests/schemas/nbool.json, tests/schemas/nfloat32.json, tests/schemas/nfloat64.json, tests/schemas/nint16.json, tests/schemas/nint32.json, tests/schemas/nint64.json, tests/schemas/nint8.json, tests/schemas/nuint16.json, tests/schemas/nuint32.json, tests/schemas/nuint64.json, tests/schemas/nuint8.json, tests/schemas/nutf8.json, tests/schemas/uint16.json, tests/schemas/uint32.json, tests/schemas/uint64.json, tests/schemas/uint8.json, tests/schemas/utf8.json, tests/test_build_utils.py
This test is back-ported from #110. It should be its own PR based on the current `main` since it ought to ensure that we did not break the current schemas.
=> Add tests for schema stability

.github/workflows/build.yml, CHANGELOG.rst
Apparently calling the publishing action twice in the same job is not supported (related [issue](https://github.com/pypa/gh-action-pypi-publish/issues/352)). This caused the publishing of the 0.10 release to fail.
=> Don't call PyPI publishing action twice in the same job

CHANGELOG.rst, tests/test_elementwise.py
The provided test case fails on the current release, but was already fixed in #120 .
=> Fix modulo operator for floating points when second arg is negative

CHANGELOG.rst, ndonnx/_typed_array/datetime.py, tests/test_datetime.py
This PR adds promotion between time units for arithmetic, comparisons, and `ndonnx.where`. It further adds support for milli and microseconds. The semantics follow those of NumPy as usual and are tested in this regard.
Closes https://github.com/Quantco/ndonnx/issues/131.
=> Extend time unit support

ndonnx/_typed_array/onnx.py
This was discovered by running array-api-tests with more examples. I'll create a PR to increase the number of examples on CI, too.
=> Fix failing test case for 'where' with one scalar value

ndonnx/_typed_array/onnx.py
Another simple fix based on an error I observed when running the array-api-tests suite with a much larger number of examples. This fixes instantiating arrays from very large Python integers when the user actually specified the data type as uint64.
=> Fix asarray for uint64 dtypes with very large integers

CHANGELOG.rst, ndonnx/_typed_array/ort_compat.py
This again showed up when running the array-api-test suite with many more examples.
=> Add missing ort_compat handling for reduce_max/reduce_min and fix changelog

CHANGELOG.rst, ndonnx/_typed_array/onnx.py
This was an oversight in the existing implementation. The produced graphs are the same either way.
=> Enable using `slice`s in setitem without value propagation

CHANGELOG.rst, ndonnx/_typed_array/onnx.py, pyproject.toml, tests/test_indexing.py
The current release of ndonnx raises an exception if a 1D boolean mask is used in in the `__setitem__` method of an array of 2 or more dimensions. This PR implements that functionality and tests it against NumPy.
=> Fix __setitem__ for boolean masks on multidimensional arrays

CHANGELOG.rst, ndonnx/_array.py, ndonnx/_typed_array/onnx.py, tests/test_indexing.py
Rather than being explicitly disallowed previously we failed with an error erroneously referring to an issue with an `Ellipsis` object in the provided key. Fixing this required some refactoring around the index validation.
=> Fix error message for fancy-slicing in setitem with int-arrays

CHANGELOG.rst, ndonnx/__init__.py, ndonnx/_array.py, ndonnx/_deprecated.py, ndonnx/_dtypes.py, ndonnx/_funcs.py, ndonnx/_propagation.py, ndonnx/_typed_array/onnx.py, ndonnx/extensions.py
These changes make it so that the file and line number presented to the user match the call site, rather than where `warn` is called.
=> Improve stack level shown in various warnings

CHANGELOG.rst, ndonnx/_funcs.py, ndonnx/_typed_array/onnx.py, ndonnx/_typed_array/typed_array.py, tests/test_free_functions.py, tests/test_manipulation_functions.py
This PR fixes `ndonnx.repeat` on our minimum supported onnxruntime 1.20.1 as surfaced in our daily CI run. The existing implementation uses (essentially) `ndonnx.max`, which raises an error on 1.20.1 for zero-sized inputs. The array-api actually [mentions](https://data-apis.org/array-api/2024.12/API_specification/generated/array_api.max.html#max) that such input is implementation-defined. The ONNX standard explicitly [defines](https://github.com/onnx/onnx/blob/main/docs/Operators.md#reducemax) the behavior. Addressing the issue of `repeat` was most easily addressed by addressing the behavior of `ndonnx.{max, min}` for zero-sized inputs.
Closes #162
=> Fix `ndx.repeat` on min-onnxruntime for zero-sized inputs

CHANGELOG.rst, ndonnx/_dtypes.py, ndonnx/_funcs.py, ndonnx/_typed_array/datetime.py, ndonnx/_typed_array/funcs.py, ndonnx/_typed_array/masked_onnx.py, ndonnx/_typed_array/onnx.py, tests/test_core.py, tests/test_creation.py, tests/test_masked.py
Possibly the most requested feature is finally here 🥳 !
This PR does what it says in the title. Array inputs are essentially passed down to the individual implementations untouched, which may return `NotImplemented`. If no `dtype` is specified but at least one argument is an `Array`, we try the array dtypes until we find one that does not return `NotImplemented`.
=> Allow arrays as inputs to ndonnx.arange
